### ISSUE TITLE
US-8: As a student, I want to set my start point for directions using the building I am currently located at.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#10]
_Set start point based on current building_

**Priority:** Important

**Acceptance Criteria:** The user can tap their current building to set as a start point. The user can select their current location (which would return their current building) in the directions menu as their start point.

**Implementation Details:** An interactable box will be mapped on the coordinates of every campus building, which will cover the current building of the user. 

![US-8](https://user-images.githubusercontent.com/45246707/75578056-28a4ae80-5a31-11ea-9bf4-84f86f7493e1.png)

**Comment by DiveshPatel** [comment]
By default, when clicking on the directions button, the origin will be current location
