### ISSUE TITLE
BG-9: Errors thrown when clicking on start or end destination in goto page.

### ISSUE THREAD

**Issue by ooms97** [MrJCipherButtles/concordi_around#104]
Actual Behavior
When selecting a room for the goto page, an error is thrown.

Steps to reproduce:

1- Click on the goto page from the maps widget (bottom right).
2- Click on start or end box.
3- Search for a room (ex: H965) and click on it.
4- Observe the following error (refer to attached image).

Expected behavior
When selecting a room, no error should appear.

![image.png](https://images.zenhubusercontent.com/5e46286cb1f25955a9d1aca3/dfa00186-5769-43c6-b433-0063e14ca226)

**Comment by DiveshPatel** [comment]
As discussed, we will be accepting this error due to the complexity of refactoring required.
