### ISSUE TITLE
US-9: As a student, I want to explore SGW and Loyola campuses so that I can gain better knowledge of the nearby amenities and services.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#11]
_The Points of Interests near both campuses are available to the user._

**Priority:** Mandatory

**Acceptance Criteria:** The user can search or view nearby points of interests on the map

**Implementation Details:** The points of interests will be imported by the Google Maps API

![US-9](https://user-images.githubusercontent.com/45246707/75578696-49213880-5a32-11ea-922c-fa9192ae5605.png)

**Comment by ChesterLY** [comment]
Missing details: What happens when you click on it? does it give info? Can you choose it as destination?
