### ISSUE TITLE
US-10: As a student, I want to toggle between SGW and Loyola campus maps.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#12]
_Toggle between the SGW and Loyola campus maps to display them both whenever the user decides to switch their view._

**Priority:** Mandatory

**Acceptance Criteria:** The user can toggle between campuses using the toggle button.

**Implementation Details:** Using the navigation widgets supplied by Flutter for Google Maps, the button will toggle between the set coordinates and zoom levels of both campus.

![US-10](https://user-images.githubusercontent.com/45246707/75578904-bd5bdc00-5a32-11ea-95fa-48620c05fd67.png)

**Comment by DiveshPatel** [comment]
Toggle button is already there in the main search bar, just add the functionality

**Comment by ChesterLY** [comment]
Tested on android device, working without bugs.
