### ISSUE TITLE
AT-4 As a student, I want to easily distinguish rooms, amenities, facilities, and services on the 8th floor, so that exploration is intuitive.

### ISSUE THREAD

**Issue by Mehrdadmaskull** [MrJCipherButtles/concordi_around#120]
**User Story**: #30 
**Acceptance Criteria**: The rooms, amenities and other points of interest are marked on the SVGs layered over the Google Maps.

**Comment by MrJCipherButtles** [comment]
I'm closing this issue because this acceptance test passed.
