### ISSUE TITLE
AT-7 As a student, I want to see my current location.

### ISSUE THREAD

**Issue by Mehrdadmaskull** [MrJCipherButtles/concordi_around#123]
**User Story**: #9 
**Acceptance Test**: When the user taps the "Current Location" button, the app will display their current location.

**Comment by MrJCipherButtles** [comment]
This acceptance test failed: No comments

**Comment by jodavimehran** [comment]
Accepted

**Comment by MrJCipherButtles** [comment]
I'm closing this issue because this acceptance test passed.
