### ISSUE TITLE
US-11: As a student, I want to get basic pop-up information on campus buildings so that I can find further details.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#13]
_Pop-ups appear when user wants to access more information about a campus building._

**Priority:** Mandatory

**Acceptance Criteria:** When the user selects a campus building or point of interest using the search bar, additional information about the building will pop-up.

**Implementation Details:** Using Flutter's widgets functionality, the coordinates of a campus building will be the limitations of the interactable zone for the widget. On hold, the additional information will display a pop-up widget in text.

**Comment by ChesterLY** [comment]
What kind of information should be displayed? Address? Phone? Facilities? Accessibility? Services?

**Comment by DiveshPatel** [comment]
We can use red markers on top of each building. When clicked on, the marker will display building information

**Comment by MrJCipherButtles** [comment]
Progress being done on Feature/building-popup by Raffi
Progress being done on Feature/map-markers by Hossein
