### ISSUE TITLE
AT-14 As a student, I want to get optimized personal motor vehicle directions to any desired building on campus.

### ISSUE THREAD

**Issue by Mehrdadmaskull** [MrJCipherButtles/concordi_around#131]
**User Story**: #18 
**Acceptance Test**: The user can choose a personal motor vehicle as their method of transportation during navigation.

**Comment by jodavimehran** [comment]
accepted

**Comment by MrJCipherButtles** [comment]
I'm closing this issue because this acceptance test passed.
