### ISSUE TITLE
AT-17 As a student, I want the outdoor (campus) map to be visually appealing and intuitive.

### ISSUE THREAD

**Issue by Mehrdadmaskull** [MrJCipherButtles/concordi_around#134]
**User Story**: #5 
**Acceptance Test**: The user can view the Google Maps and the widgets are overlayed on top of the map.

**Comment by jodavimehran** [comment]
accepted

**Comment by MrJCipherButtles** [comment]
I'm closing this issue because this acceptance test passed.
