### ISSUE TITLE
AT-18 As a student, I want to enter my start and end buildings by search.

### ISSUE THREAD

**Issue by Mehrdadmaskull** [MrJCipherButtles/concordi_around#135]
**User Story**: #20 
**Acceptance Test**: The user can set start and end points as buildings through the navigation search menu. When the user only chooses a destination, the user's current location will be used by default as the starting location.

**Comment by jodavimehran** [comment]
accepted

**Comment by MrJCipherButtles** [comment]
I'm closing this issue because this acceptance test passed.
