### ISSUE TITLE
US-22: As a student, I want directions to my next class.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#25]
_Set end point based on next class_

**Priority:** Mandatory

**Acceptance Criteria:** When the user selects a class from the "Calendar" menu, the directions to that class will be displayed.

**Implementation Details:** The Google Calendar API will be implemented into the application in order to pull the standardized class specifications (course, location, hours). The information will be available in the "Calendar" menu of the app. Each class block will be interactable, and when a class is selected, the room information will be passed onto the search widget, and the directions to the class will be available once a starting point is set.

![US-22](https://user-images.githubusercontent.com/45246707/75581857-5e996100-5a38-11ea-92d1-2fde840ae107.png)

**Comment by RumianR** [comment]
Addressed in Feature next class #151
