### ISSUE TITLE
US-23: As a student, I want a list of 8th floors rooms, amenities, and services.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#29]
_Create a list that has all of 8th floors points of interests and classrooms that appears during search._

**Priority:** Mandatory

**Acceptance Criteria:** The user can access a list of the floors'  rooms and POIs in the search bar.

**Implementation Details:** The search widget will be connected to the back-end database with the specifications of rooms and buildings, and display them as a list. 

![US-23](https://user-images.githubusercontent.com/45246707/75504301-129ddc00-59a6-11ea-95f6-fd30c50d662f.png)

**Comment by EspressoCode** [comment]
You may find the coordinates of some of the rooms + 2 main wash rooms, escalators and important point for the path.
The map layer and points can be seen at:
https://drive.google.com/open?id=1dKeCCFCwsI_W1-5BLOPWGyM1wVlU0dRW&usp=sharing

The naming convention is:
P for path, LL for lower left corner, MR for middle right, ESC-D for escalator going down, ESC-U for escalator going up, Men and Women defines which type of washroom it is. 
The extracted coordinates can be seen on the attached CSV file.
[Coordinates.xlsx](https://github.com/MrJCipherButtles/concordi_around/files/4216646/Coordinates.xlsx)
