### ISSUE TITLE
US-28: As a student with disabilities I want to get the disability path between a building’s rooms, amenities, services, etc.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#34]
_Indoor directions for disabled students._

**Priority:** Mandatory

**Acceptance Criteria:** The path drawn considers that the user may have some disability, and will adjust to conform to their needs, by prioritizing elevators over stairs and escalators.

**Implementation Details:** The custom algorithm will have a "disability" Boolean attribute that will determine the path according to the attribute (0 would mean a regular path is fine, 1 would mean a disability path is required).

**Comment by ChesterLY** [comment]
I will be adding the disability checkbox on the app drawer.
