### ISSUE TITLE
Evaluate ui mockups

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#4]
Let's discuss the created mock-ups to come to a consensus

**Comment by ChesterLY** [comment]
Link for the final mockup that will include the elements desired by the Product Owner:
https://www.figma.com/file/rfiUTh2GkeCBAvtW3bqoak/ConcordiAround-(UI-TeamWork)?node-id=0%3A1

**Comment by GaroBal** [comment]
As @ChesterLY pointed out, the final mockup is [this](https://www.figma.com/file/rfiUTh2GkeCBAvtW3bqoak/ConcordiAround-(UI-TeamWork)?node-id=441%3A144). I will close the issue since the mockup is now complete
