### ISSUE TITLE
US-3: As a student, I want the settings page to be visually appealing and intuitive.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#42]
_This user story covers the settings menu interface. This applies to the side menu that appears after interacting with the "hamburger" button._

**Priority:** Important

**Acceptance Criteria:** The user can identify the settings menu and its components.

**Implementation Details:** By using a widgets associated with the menu button, and overlay of the settings menu will appear on top of any interface the user is currently on (whether they are on indoor or outdoor interface).

![US-3](https://user-images.githubusercontent.com/45246707/75575307-e5950c00-5a2d-11ea-99c2-aed91d7e5775.png)

**Comment by DiveshPatel** [comment]
As discussed, this issue is closed since we do not have a need for a settings page for this sprint.
