### ISSUE TITLE
BG-2: Floor selector does not meet mockups design

### ISSUE THREAD

**Issue by DiveshPatel** [MrJCipherButtles/concordi_around#58]
Actual Behaviour
The floor selector is on the bottom left side

Steps to reproduce: 
1. Zoom into the vicinity of the hall building where the floor selector will show up
2. The floor is on the bottom left of the screen

Expected behaviour
The floor selector should pop up on the right side above the current location floating action button

![87852848_769744123429309_4533419778580152320_n.jpg](https://images.zenhubusercontent.com/5e49b32d14923743897b0580/73989eb1-baf5-4d5f-b2ef-8d56dd3c5c44)

**Comment by GaroBal** [comment]
We decided that it looks much better in the bottom left layout, so let's stick with it as it is now in the implementation.
