### ISSUE TITLE
US-5: As a student, I want a list of all campus buildings.

### ISSUE THREAD

**Issue by MrJCipherButtles** [MrJCipherButtles/concordi_around#7]
_A list of the campus buildings that the user can access to choose a point from._

**Priority:** Mandatory

**Acceptance Criteria:** The user can search through a list of the campus buildings.

**Implementation Details:** When the user selects to search a building, there will be a drop down list that will appear with all the campus buildings, which will also be searchable to narrow down to a specific building.
![US-5](https://user-images.githubusercontent.com/45246707/75500925-5ee41e80-599c-11ea-8583-77a9b0421530.PNG)

**Comment by ChesterLY** [comment]
Link to the Firestore Database for the building/room list:
https://console.firebase.google.com/u/0/project/concordiaround-soen390/database/firestore/data~2F

**Comment by ChesterLY** [comment]
Alternate Database framework is used, Firestore Database is deprecated
