### ISSUE TITLE
BG-7: Submitting search throws an error.

### ISSUE THREAD

**Issue by ooms97** [MrJCipherButtles/concordi_around#71]
Actual Behaviour
When submitting a search for a room, the app crashes.

Steps to reproduce:

1- Click on search bar.
2- Submit search (can be empty or non-empty).
3- App crashes

Expected behaviour
After submitting search, app should not crash.

![88350751_824088251429767_2245344194371518464_n](https://user-images.githubusercontent.com/46823895/75619347-c76ffe80-5b48-11ea-8e72-f54d31970d21.jpg)

![89006624_219530199440493_6863935927505387520_n](https://user-images.githubusercontent.com/46823895/75619351-cf2fa300-5b48-11ea-9f8e-da1259a0111e.jpg)

![89048367_2643510165925094_5005043999845646336_n](https://user-images.githubusercontent.com/46823895/75619353-d48ced80-5b48-11ea-9105-da6f763ea48c.jpg)

**Comment by DiveshPatel** [comment]
This bug was addressed in the linked PR.
