### ISSUE TITLE
BG-8: Goto_page snackbar

### ISSUE THREAD

**Issue by ChesterLY** [MrJCipherButtles/concordi_around#87]
Actual Behaviour
When user doesn't set a destination on the goto page, there is no warning/notification

Steps to reproduce:

1- Press on the direction button (underneath the location button)
2- Press on the GO button without setting anything on the destination search bar

Expected behavior
A snackbar notification should appear at the bottom of the page when the user tries to get direction without having a destination set

**Comment by DiveshPatel** [comment]
Resolved
